# Generated by Django 5.2.8 on 2025-11-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_role',
            field=models.CharField(blank=True, choices=[('backend_dev', 'Backend Developer'), ('frontend_dev', 'Frontend Developer'), ('fullstack_dev', 'Fullstack Developer'), ('qa', 'QA Tester'), ('devops', 'DevOps Engineer'), ('uiux', 'UI/UX Designer'), ('pm', 'Project Manager'), ('tl', 'Team Lead'), ('architect', 'Software Architect'), ('intern', 'Intern')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
