# Generated by Django 5.2.8 on 2025-11-26 05:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at_project_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('user', 'project')},
        ),
    ]
