# Generated by Django 5.2.9 on 2025-12-10 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_alter_project_options_alter_projectmember_options_and_more'),
        ('tasks', '0003_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('assign', 'Assigned'), ('comment', 'Commented'), ('status_change', 'Status Changed'), ('member_add', 'Member Added'), ('member_remove', 'Member Removed'), ('member_role_change', 'Member Role Changed')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_a_created_b5efc6_idx'), models.Index(fields=['project', '-created_at'], name='analytics_a_project_907269_idx'), models.Index(fields=['task', '-created_at'], name='analytics_a_task_id_ad25c7_idx'), models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_abe786_idx')],
            },
        ),
    ]
